version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=manageDB
    depends_on:
      - mysqlDB
    command: npm run dev  # Assuming you're using nodemon for development

  mysqlDB:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./backend/mysql_data:/var/lib/mysql  # Ensure the correct path for MySQL data persistence
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: manageDB
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run start

volumes:
  mysql_data:
